# Generated by Django 2.1.2 on 2019-01-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_product',
            field=models.ImageField(default='', upload_to='static/images/'),
        ),
    ]
