# Generated by Django 2.1.2 on 2019-01-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productcompanion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Размер товара',
                'verbose_name_plural': 'Размер товара',
            },
        ),
        migrations.AlterModelOptions(
            name='productcompanion',
            options={'verbose_name': 'Сопутствующий товар', 'verbose_name_plural': 'Сопутствующие товары'},
        ),
    ]
