# Generated by Django 2.1.2 on 2019-01-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_sizeprod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
