# Generated by Django 2.1.2 on 2019-01-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20190117_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeprod',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product', to='product.SizeProd'),
        ),
    ]
