# Generated by Django 2.1.2 on 2019-01-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20190117_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeprod',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
