# Generated by Django 2.1.2 on 2019-01-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190117_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeprod',
            name='smoll_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sizeprod',
            name='smoll_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sizeprod',
            name='smoll_s',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
