# Generated by Django 2.1.2 on 2019-01-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20190117_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sizeprod',
            old_name='smoll_l',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='sizeprod',
            name='smoll_m',
        ),
        migrations.RemoveField(
            model_name='sizeprod',
            name='smoll_s',
        ),
    ]
