# Generated by Django 2.1.2 on 2019-02-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_recording'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image_product', models.ImageField(default='', upload_to='static/images/')),
                ('smoll_s', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('smoll_m', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('smoll_l', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sizeprod', models.ManyToManyField(blank=True, related_name='buket', to='product.SizeProd')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'verbose_name': 'Товар',
            },
        ),
    ]
