# Generated by Django 2.1.2 on 2019-02-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20190210_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Подарочная корзина', 'verbose_name_plural': 'подарочные корзины'},
        ),
        migrations.AddField(
            model_name='basket',
            name='image_product',
            field=models.ImageField(default='', upload_to='static/images/'),
        ),
    ]
