# Generated by Django 2.1.2 on 2019-02-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20190210_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name': 'Категория товара', 'verbose_name_plural': 'категория товаровв'},
        ),
    ]
