# Generated by Django 2.1.2 on 2019-02-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20190210_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Air',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(default='', upload_to='static/images/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=True, to='product.CategoryProduct')),
            ],
            options={
                'verbose_name': 'Воздушный шарик',
                'verbose_name_plural': 'Воздушные шарики',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Фруктовый букет', 'verbose_name_plural': 'Фруктовые букеты'},
        ),
    ]
