# Generated by Django 2.1.2 on 2019-02-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20190218_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='air',
            old_name='image',
            new_name='image_air',
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='image',
            new_name='image_basket',
        ),
        migrations.RenameField(
            model_name='buket',
            old_name='image_product',
            new_name='image_buket',
        ),
        migrations.RenameField(
            model_name='chocolate',
            old_name='image',
            new_name='image_chocolate',
        ),
        migrations.AlterField(
            model_name='buket',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
