# Generated by Django 2.1.2 on 2019-02-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20190221_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcompanion',
            old_name='image_product',
            new_name='image_companion',
        ),
    ]
