# Generated by Django 2.1.2 on 2019-02-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20190224_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcompanion',
            name='session_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
